In [1]:
import os
import warnings

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [3]:
BASE_DIR = os.path.dirname(os.getcwd())

DATA_PATH = os.path.join(
    BASE_DIR,
    "data",
    "raw",
    "owid-covid-data (1).csv",
)

print(f"Dataset Path: {DATA_PATH}")

Dataset Path: c:\Users\roshi\Downloads\REAL_WORLD_PROJECTS\covid19-data-analysis-visualization-main (2)\covid19-data-analysis-visualization-main\covid19-data-analysis-visualization-main\data\raw\owid-covid-data (1).csv

In [4]:
df = pd.read_csv(DATA_PATH)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [5]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(44785, 41)

In [6]:
df.head()

  iso_code continent     location        date  total_cases  new_cases  new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  total_cases_per_million  new_cases_per_million  new_cases_smoothed_per_million  total_deaths_per_million  new_deaths_per_million  new_deaths_smoothed_per_million  new_tests  total_tests  total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  new_tests_smoothed_per_thousand  tests_per_case  positive_rate tests_units  stringency_index  population  population_density  median_age  aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index
0      AFG      Asia  Afghanistan  2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
1      AFG      Asia  Afghanistan  2020-01-01          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
2      AFG      Asia  Afghanistan  2020-01-02          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
3      AFG      Asia  Afghanistan  2020-01-03          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
4      AFG      Asia  Afghanistan  2020-01-04          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498

In [7]:
df.tail()

      iso_code continent       location        date  total_cases  new_cases  new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  total_cases_per_million  new_cases_per_million  new_cases_smoothed_per_million  total_deaths_per_million  new_deaths_per_million  new_deaths_smoothed_per_million  new_tests  total_tests  total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  new_tests_smoothed_per_thousand  tests_per_case  positive_rate tests_units  stringency_index  population  population_density  median_age  aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index
44780      NaN       NaN  International  2020-09-15        696.0        NaN                 NaN           7.0         NaN                  NaN                      NaN                    NaN                             NaN                       NaN                     NaN                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN         NaN                 NaN         NaN            NaN            NaN             NaN              NaN                    NaN                  NaN             NaN           NaN                     NaN                         NaN              NaN                      NaN
44781      NaN       NaN  International  2020-09-16        696.0        NaN                 NaN           7.0         NaN                  NaN                      NaN                    NaN                             NaN                       NaN                     NaN                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN         NaN                 NaN         NaN            NaN            NaN             NaN              NaN                    NaN                  NaN             NaN           NaN                     NaN                         NaN              NaN                      NaN
44782      NaN       NaN  International  2020-09-17        696.0        NaN                 NaN           7.0         NaN                  NaN                      NaN                    NaN                             NaN                       NaN                     NaN                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN         NaN                 NaN         NaN            NaN            NaN             NaN              NaN                    NaN                  NaN             NaN           NaN                     NaN                         NaN              NaN                      NaN
44783      NaN       NaN  International  2020-09-18        696.0        NaN                 NaN           7.0         NaN                  NaN                      NaN                    NaN                             NaN                       NaN                     NaN                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN         NaN                 NaN         NaN            NaN            NaN             NaN              NaN                    NaN                  NaN             NaN           NaN                     NaN                         NaN              NaN                      NaN
44784      NaN       NaN  International  2020-09-19        696.0        NaN                 NaN           7.0         NaN                  NaN                      NaN                    NaN                             NaN                       NaN                     NaN                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN         NaN                 NaN         NaN            NaN            NaN             NaN              NaN                    NaN                  NaN             NaN           NaN                     NaN                         NaN              NaN                      NaN

In [8]:
print(df.columns.tolist())

['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44785 entries, 0 to 44784
Data columns (total 41 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   iso_code                         44521 non-null  object
 1   continent                        44257 non-null  object
 2   location                         44785 non-null  object
 3   date                             44785 non-null  object
 4   total_cases                      44182 non-null  float64
 5   new_cases                        43982 non-null  float64
 6   new_cases_smoothed               43200 non-null  float64
 7   total_deaths                     44182 non-null  float64
 8   new_deaths                       43982 non-null  float64
 9   new_deaths_smoothed              43200 non-null  float64
 10  total_cases_per_million          43918 non-null  float64
 11  new_cases_per_million            43918 non-null  float64
 12  new_cases_smoothed_per_million   43135 non-null  float64
 13  total_deaths_per_million         43918 non-null  float64
 14  new_deaths_per_million           43918 non-null  float64
 15  new_deaths_smoothed_per_million  43135 non-null  float64
 16  new_tests                        15647 non-null  float64
 17  total_tests                      16022 non-null  float64
 18  total_tests_per_thousand         16022 non-null  float64
 19  new_tests_per_thousand           15647 non-null  float64
 20  new_tests_smoothed               17568 non-null  float64
 21  new_tests_smoothed_per_thousand  17568 non-null  float64
 22  tests_per_case                   16149 non-null  float64
 23  positive_rate                    16533 non-null  float64
 24  tests_units                      18374 non-null  object
 25  stringency_index                 37057 non-null  float64
 26  population                       44521 non-null  float64
 27  population_density               42502 non-null  float64
 28  median_age                       39952 non-null  float64
 29  aged_65_older                    39360 non-null  float64
 30  aged_70_older                    39745 non-null  float64
 31  gdp_per_capita                   39442 non-null  float64
 32  extreme_poverty                  26322 non-null  float64
 33  cardiovasc_death_rate            39967 non-null  float64
 34  diabetes_prevalence              41366 non-null  float64
 35  female_smokers                   31358 non-null  float64
 36  male_smokers                     30963 non-null  float64
 37  handwashing_facilities           18658 non-null  float64
 38  hospital_beds_per_thousand       36139 non-null  float64
 39  life_expectancy                  43963 non-null  float64
 40  human_development_index          38558 non-null  float64
dtypes: float64(36), object(5)
memory usage: 14.0+ MB

In [10]:
df.columns = [
    col.strip().lower()
    for col in df.columns
]

print(df.columns.tolist())

['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index']

In [11]:
COLUMN_MAPPING = {
    "location": "country",
    "entity": "country",
    "day": "date",
    "cases": "new_cases",
    "deaths": "new_deaths",
    "vaccinations": "total_vaccinations",
}

for old_col, new_col in COLUMN_MAPPING.items():

    if old_col in df.columns:

        df.rename(
            columns={old_col: new_col},
            inplace=True
        )

print(df.columns.tolist())

['iso_code', 'continent', 'country', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index']

In [12]:
required_columns = [
    "country",
    "date",
    "new_cases",
    "new_deaths",
    "total_vaccinations",
]

for col in required_columns:

    if col in df.columns:

        print(f"{col} --> PRESENT")

    else:

        print(f"{col} --> MISSING")

country --> PRESENT
date --> PRESENT
new_cases --> PRESENT
new_deaths --> PRESENT
total_vaccinations --> MISSING

In [13]:
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

print(df["date"].head())

0   2019-12-31
1   2020-01-01
2   2020-01-02
3   2020-01-03
4   2020-01-04
Name: date, dtype: datetime64[ns]

In [14]:
df.isnull().sum()

iso_code                             264
continent                            528
country                                0
date                                   0
total_cases                          603
new_cases                            803
new_cases_smoothed                  1585
total_deaths                         603
new_deaths                           803
new_deaths_smoothed                 1585
total_cases_per_million              867
new_cases_per_million                867
new_cases_smoothed_per_million      1650
total_deaths_per_million             867
new_deaths_per_million               867
new_deaths_smoothed_per_million     1650
new_tests                          29138
total_tests                        28763
total_tests_per_thousand           28763
new_tests_per_thousand             29138
new_tests_smoothed                 27217
new_tests_smoothed_per_thousand    27217
tests_per_case                     28636
positive_rate                      28252
tests_units                        26411
stringency_index                    7728
population                           264
population_density                  2283
median_age                          4833
aged_65_older                       5425
aged_70_older                       5040
gdp_per_capita                      5343
extreme_poverty                    18463
cardiovasc_death_rate               4818
diabetes_prevalence                 3419
female_smokers                     13427
male_smokers                       13822
handwashing_facilities             26127
hospital_beds_per_thousand          8646
life_expectancy                      822
human_development_index             6227
dtype: int64

In [15]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows: {duplicates}")

Duplicate Rows: 0

In [16]:
df.drop_duplicates(inplace=True)

print("Duplicates Removed Successfully")

Duplicates Removed Successfully

In [17]:
numeric_columns = [
    "new_cases",
    "new_deaths",
    "total_vaccinations",
]

for col in numeric_columns:

    if col in df.columns:

        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        ).fillna(0)

In [18]:
df["country"] = (
    df["country"]
    .astype(str)
    .fillna("Unknown")
)

In [19]:
df.describe()

        total_cases      new_cases  new_cases_smoothed   total_deaths    new_deaths  new_deaths_smoothed  total_cases_per_million  new_cases_per_million  new_cases_smoothed_per_million  total_deaths_per_million  new_deaths_per_million  new_deaths_smoothed_per_million     new_tests   total_tests  total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  new_tests_smoothed_per_thousand  tests_per_case  positive_rate  stringency_index    population  population_density    median_age  aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index
count  4.418200e+04   44785.000000        43200.000000   44182.000000  44785.000000         43200.000000             43918.000000           43918.000000                    43135.000000              43918.000000            43918.000000                     43135.000000  1.564700e+04  1.602200e+04              16022.000000            15647.000000        1.756800e+04                     17568.000000    16149.000000   16533.000000      37057.000000  4.452100e+04        42502.000000  39952.000000   39360.000000   39745.000000    39442.000000     26322.000000           39967.000000         41366.000000    31358.000000  30963.000000            18658.000000                36139.000000     43963.000000             38558.000000
mean   9.372153e+04    1363.869421         1372.258368    3885.163189     42.546567            43.329499              1778.176471              23.573850                       23.160618                 55.320410                0.561956                         0.561161  2.208545e+04  1.386639e+06                 48.113417                0.668168        2.126301e+04                         0.644681      178.872316       0.063482         57.679960  8.912545e+07          361.318045     31.360570       9.280353       5.871494    20979.943732        12.029018             251.347231             8.048869       10.834007     32.637049               52.576272                    3.115428        74.052595                 0.725580
std    9.707004e+05   12552.748824        12420.794948   36227.966483    363.298805           356.193423              3814.416468              72.289186                       55.613758                140.662359                3.048089                         1.930438  9.003979e+04  6.153869e+06                 87.591594                1.130880        8.268074e+04                         1.020659      922.324049       0.089607         27.729892  6.156841e+08         1660.883709      9.022312       6.325487       4.320656    20466.166309        19.158253             117.620708             4.143192       10.481952     13.408593               31.579386                    2.530433         7.364382                 0.152673
min    0.000000e+00   -8261.000000         -552.000000       0.000000  -1918.000000          -232.143000                 0.000000           -2212.545000                     -269.978000                  0.000000              -67.901000                        -9.678000 -3.743000e+03  1.000000e+00                  0.000000               -0.398000        0.000000e+00                         0.000000        1.535000       0.000000          0.000000  8.090000e+02            0.137000     15.100000       1.144000       0.526000      661.240000         0.100000              79.370000             0.990000        0.100000      7.700000                1.188000                    0.100000        53.280000                 0.354000
25%    5.300000e+01       0.000000            0.571000       0.000000      0.000000             0.000000                25.373750               0.000000                        0.123000                  0.000000                0.000000                         0.000000  9.510000e+02  4.339200e+04                  2.565250                0.060000        1.053750e+03                         0.063000       12.172000       0.008000         38.890000  1.402985e+06           38.170250     23.500000       3.556000       2.142000     5338.454000         0.500000             155.898000             5.310000        1.900000     21.400000               21.222000                    1.300000        69.910000                 0.606000
50%    9.370000e+02       8.000000           14.143000      17.000000      0.000000             0.143000               266.509000               1.475500                        2.838000                  4.566000                0.000000                         0.018000  3.174000e+03  1.803585e+05                 13.466000                0.275000        3.570000e+03                         0.298000       33.977000       0.028000         64.350000  8.654618e+06           88.125000     31.400000       6.981000       4.419000    14103.452000         1.800000             238.339000             7.110000        6.400000     31.400000               55.182000                    2.500000        75.490000                 0.755000
75%    9.989000e+03     148.000000          160.857000     213.000000      3.000000             3.000000              1793.012500              16.551500                       18.200500                 33.616750                0.197000                         0.276000  1.173300e+04  7.016060e+05                 55.923000                0.807500        1.242500e+04                         0.810000      109.459000       0.080000         79.630000  3.107294e+07          214.243000     39.700000      14.762000       9.473000    32415.132000        16.000000             318.949000            10.180000       19.600000     40.900000               83.741000                    4.200000        79.930000                 0.853000
max    3.054045e+07  313658.000000       288630.000000  952724.000000  10491.000000          7456.714000             42663.811000            4944.376000                      882.924000               1237.551000              215.382000                        63.140000  1.239166e+06  1.010467e+08                855.878000               16.574000        1.098274e+06                        12.502000    47299.000000       0.651000        100.000000  7.794799e+09        19347.500000     48.200000      27.049000      18.493000   116935.600000        77.600000             724.417000            23.360000       44.000000     78.100000               98.999000                   13.800000        86.750000                 0.953000

In [20]:
unique_countries = df["country"].nunique()

print(f"Total Unique Countries: {unique_countries}")

Total Unique Countries: 212

In [21]:
min_date = df["date"].min()

max_date = df["date"].max()

print(f"Start Date: {min_date}")

print(f"End Date: {max_date}")

Start Date: 2019-12-31 00:00:00
End Date: 2020-09-19 00:00:00

In [22]:
top_cases = (
    df.groupby("country")["new_cases"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_cases

country
World            30540446.0
United States     6724667.0
India             5308014.0
Brazil            4495183.0
Russia            1091186.0
Peru               756412.0
Colombia           750471.0
Mexico             688954.0
South Africa       657627.0
Spain              640040.0
Name: new_cases, dtype: float64

In [23]:
top_deaths = (
    df.groupby("country")["new_deaths"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_deaths

country
World             952724.0
United States     198589.0
Brazil            135793.0
India              85619.0
Mexico             72803.0
United Kingdom     41732.0
Italy              35668.0
Peru               31283.0
France             31249.0
Spain              30495.0
Name: new_deaths, dtype: float64

In [24]:
top_vaccinations = (
    df.groupby("country")["total_vaccinations"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_vaccinations

KeyError: 'Column not found: total_vaccinations'

In [ ]:
global_trend = (
    df.groupby("date")[
        [
            "new_cases",
            "new_deaths",
            "total_vaccinations"
        ]
    ]
    .sum()
    .reset_index()
)

global_trend.head()

KeyError: "Columns not found: 'total_vaccinations'"

In [ ]:
plt.figure(figsize=(14, 6))

plt.plot(
    global_trend["date"].values,
    global_trend["new_cases"].values
)

plt.title("Global COVID-19 Cases Over Time")

plt.xlabel("Date")

plt.ylabel("New Cases")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

NameError: name 'global_trend' is not defined

In [25]:
plt.figure(figsize=(14, 6))

plt.plot(
    global_trend["date"].values,
    global_trend["new_deaths"].values
)

plt.title("Global COVID-19 Deaths Over Time")

plt.xlabel("Date")

plt.ylabel("New Deaths")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

NameError: name 'global_trend' is not defined

In [ ]:
plt.figure(figsize=(14, 6))

plt.plot(
    global_trend["date"].values,
    global_trend["total_vaccinations"].values
)

plt.title("Global COVID-19 Vaccinations Over Time")

plt.xlabel("Date")

plt.ylabel("Vaccinations")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

NameError: name 'global_trend' is not defined

In [26]:
latest_date = df["date"].max()

latest_df = df[
    df["date"] == latest_date
]

hotspots = latest_df.sort_values(
    by="new_cases",
    ascending=False
).head(10)

hotspots[
    [
        "country",
        "new_cases",
        "new_deaths"
    ]
]

             country  new_cases  new_deaths
44520          World   309076.0      5947.0
18959          India    93337.0      1247.0
42376  United States    50209.0       956.0
6025          Brazil    39797.0       858.0
14636         France    13215.0       154.0
1683       Argentina    12701.0       262.0
9074        Colombia     6526.0       185.0
31940           Peru     6314.0       137.0
33573         Russia     5905.0       134.0
26596         Mexico     4841.0       624.0

In [ ]:
PROCESSED_DATA_PATH = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "cleaned_covid_data.csv"
)

df.to_csv(
    PROCESSED_DATA_PATH,
    index=False
)

print(f"Saved To: {PROCESSED_DATA_PATH}")

Saved To: c:\Users\roshi\Downloads\REAL_WORLD_PROJECTS\covid19-data-analysis-visualization-main (2)\covid19-data-analysis-visualization-main\covid19-data-analysis-visualization-main\data\processed\cleaned_covid_data.csv

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44785 entries, 0 to 44784
Data columns (total 41 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   iso_code                         44521 non-null  object
 1   continent                        44257 non-null  object
 2   country                          44785 non-null  object
 3   date                             44785 non-null  datetime64[ns]
 4   total_cases                      44182 non-null  float64
 5   new_cases                        44785 non-null  float64
 6   new_cases_smoothed               43200 non-null  float64
 7   total_deaths                     44182 non-null  float64
 8   new_deaths                       44785 non-null  float64
 9   new_deaths_smoothed              43200 non-null  float64
 10  total_cases_per_million          43918 non-null  float64
 11  new_cases_per_million            43918 non-null  float64
 12  new_cases_smoothed_per_million   43135 non-null  float64
 13  total_deaths_per_million         43918 non-null  float64
 14  new_deaths_per_million           43918 non-null  float64
 15  new_deaths_smoothed_per_million  43135 non-null  float64
 16  new_tests                        15647 non-null  float64
 17  total_tests                      16022 non-null  float64
 18  total_tests_per_thousand         16022 non-null  float64
 19  new_tests_per_thousand           15647 non-null  float64
 20  new_tests_smoothed               17568 non-null  float64
 21  new_tests_smoothed_per_thousand  17568 non-null  float64
 22  tests_per_case                   16149 non-null  float64
 23  positive_rate                    16533 non-null  float64
 24  tests_units                      18374 non-null  object
 25  stringency_index                 37057 non-null  float64
 26  population                       44521 non-null  float64
 27  population_density               42502 non-null  float64
 28  median_age                       39952 non-null  float64
 29  aged_65_older                    39360 non-null  float64
 30  aged_70_older                    39745 non-null  float64
 31  gdp_per_capita                   39442 non-null  float64
 32  extreme_poverty                  26322 non-null  float64
 33  cardiovasc_death_rate            39967 non-null  float64
 34  diabetes_prevalence              41366 non-null  float64
 35  female_smokers                   31358 non-null  float64
 36  male_smokers                     30963 non-null  float64
 37  handwashing_facilities           18658 non-null  float64
 38  hospital_beds_per_thousand       36139 non-null  float64
 39  life_expectancy                  43963 non-null  float64
 40  human_development_index          38558 non-null  float64
dtypes: datetime64[ns](1), float64(36), object(4)
memory usage: 14.4+ MB

In [ ]:
print("COVID-19 Data Exploration Completed Successfully")

COVID-19 Data Exploration Completed Successfully

In [ ]:
,27,26,25,24,59